name: Reclaim disk space
description: Deletes non-essential files from the runner to reclaim disk space

runs:
  using: composite
  steps:
    - name: Reclaim disk space
      shell: bash
      run: |
        set -eux

        # Purge snaps.
        sudo snap remove --purge $(snap list | awk '!/^Name|^core|^snapd/ {print $1}')

        # This was inspired from https://github.com/easimon/maximize-build-space
        df -h /

        # dotnet
        sudo rm -rf /usr/share/dotnet
        # android
        sudo rm -rf /usr/local/lib/android
        # haskell
        sudo rm -rf /opt/ghc
        # codeql
        sudo rm -rf /opt/hostedtoolcache/CodeQL

        df -h /
